# SITE CONFIGURATION
title: Vitali Set # your site title
author: O conjunto de Vitali # You :P
# description: > # Meta description of Homepage
#  AAAAAAAAAAAAAAAA
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vitaliset.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Vitali Set
  links:
    - https://www.linkedin.com/in/carlo-lemos-946592188
    - https://github.com/vitaliset/

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Início', link: '/'}
  - {name: 'Sobre', link: '/sobre'}

#tagline: >
#  My thoughts and experiments on machine learning and related stuff

hero_img: teste1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: vitaliset@gmail.com # email for form submission

github_username:  vitaliset # replace with your_github_username or comment to remove link from footer
# linkedin_username: gdmarmerola

disqus:
  shortname: vitaliset # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
